// Auto-generated per-build VMP configuration — DO NOT COMMIT
// Each APK build gets randomized algorithm constants.
// Generated by gen_payload_cpp.py at build time.

#ifndef YUNIAN_VMP_CONFIG_H
#define YUNIAN_VMP_CONFIG_H

#include <stdint.h>

// ── LCG parameters for scatter_key_positions ──────────────────────
// state = (state * VMP_LCG_MUL + VMP_LCG_ADD) & 0xFFFFFFFF
#define VMP_LCG_MUL  0xD196C00Bu
#define VMP_LCG_ADD  0x477CD1B6u

// ── XOR deobfuscation parameters for deobfuscate_key ──────────────
// key_out[i] = obf_key[i] ^ seed[(i * VMP_XOR_STRIDE) & 3] ^ (i * VMP_XOR_MULT)
#define VMP_XOR_MULT    0x97u
#define VMP_XOR_STRIDE  0x04u

// ── Integrity seed multiplier (vm-engine.cpp vm_init) ─────────────
// Replaces hardcoded 1103515245 with per-build random value.
#define VMP_INTEGRITY_MUL  0x7E87B7EDu

// ── Seed (cert CRC32, for reference only — not used at runtime) ───
#define VMP_BUILD_SEED  0xBDBEFB3Fu

// ── Shell method/field name obfuscation (per-build random) ─────────
// These replace the hardcoded JNI names in Kotlin shell + C++ gMethods.
// C++:  RegisterNatives with VMP_SHELL_LOAD_PAYLOAD instead of "nativeLoadPayload"
//       GetStaticFieldID with VMP_SHELL_DEX_LOADER instead of "sDexClassLoader"
//       GetStaticFieldID with VMP_SHELL_REAL_APP_CLASS instead of "sRealAppClass"
// Kotlin: external fun dRil1PU2xgjykWt(...) replaces nativeLoadPayload
//         @JvmStatic var eTfEpNttyxA94gtiO replaces sDexClassLoader
//         @JvmStatic var fvlzLBmb6kQl1sV replaces sRealAppClass
#define VMP_SHELL_LOAD_PAYLOAD   "dRil1PU2xgjykWt"
#define VMP_SHELL_DEX_LOADER     "eTfEpNttyxA94gtiO"
#define VMP_SHELL_REAL_APP_CLASS "fvlzLBmb6kQl1sV"


// ── Per-build VMP opcode mapping (randomized per APK) ──
// Seed: 0xBDBEFB3F
#define VMP_OP_ADD 0x12
#define VMP_OP_ADD_IMM 0xD9
#define VMP_OP_AND 0xC5
#define VMP_OP_CALL 0xAA
#define VMP_OP_CMP 0x4E
#define VMP_OP_CMP_IMM 0x0A
#define VMP_OP_GFMUL 0xA7
#define VMP_OP_HALT 0xFF
#define VMP_OP_HYPERCALL 0xCC
#define VMP_OP_JE 0x7B
#define VMP_OP_JG 0xD0
#define VMP_OP_JGE 0x6B
#define VMP_OP_JL 0xBD
#define VMP_OP_JMP 0xDD
#define VMP_OP_JNE 0xB8
#define VMP_OP_LOAD_IMM 0xC2
#define VMP_OP_LOAD_MEM 0xBC
#define VMP_OP_LOAD_REG 0x60
#define VMP_OP_MUL 0xA1
#define VMP_OP_MUL_IMM 0xC0
#define VMP_OP_NOP 0x78
#define VMP_OP_OR 0x77
#define VMP_OP_RET 0xB6
#define VMP_OP_SBOX 0xFB
#define VMP_OP_SHL 0xA0
#define VMP_OP_SHR 0x4C
#define VMP_OP_STORE_MEM 0x35
#define VMP_OP_STORE_REG 0x38
#define VMP_OP_SUB 0xAE
#define VMP_OP_XOR 0xEC
#define VMP_OP_XTIME 0x40

#endif // YUNIAN_VMP_CONFIG_H