// SM4 block cipher — internal implementation header (dev stub).
// Auto-generated by tools/sm4_tool.cpp at build time.
// Real impl is in sm-cipher.cpp/h; this header provides extra internal helpers.
#pragma once

#include "sm-cipher.h"

// Additional internal helpers that build tools may inline/config
#ifdef __cplusplus
extern "C" {
#endif

// Alias: sm4_key_expand = sm4_key_schedule (VM engine compatibility)
#define sm4_key_expand(key, rk) sm4_key_schedule(key, rk)

// Convenience wrappers matching sm-cipher signatures
static inline void sm4_encrypt(const uint8_t key[SM4_KEY_SIZE], const uint8_t in[SM4_BLOCK_SIZE], uint8_t out[SM4_BLOCK_SIZE]) {
    uint32_t rk[SM4_ROUNDS];
    sm4_key_schedule(key, rk);
    sm4_encrypt_block(in, rk, out);
}

static inline void sm4_decrypt(const uint8_t key[SM4_KEY_SIZE], const uint8_t in[SM4_BLOCK_SIZE], uint8_t out[SM4_BLOCK_SIZE]) {
    uint32_t rk[SM4_ROUNDS];
    sm4_key_schedule(key, rk);
    sm4_decrypt_block(in, rk, out);
}

#ifdef __cplusplus
}
#endif
