/*
 * Pre-compiled VM bytecode — generated by tools/vm_bytecode.py
 *
 * These bytecode programs are embedded in the native library
 * at compile time. The original C functions they replace are
 * never present in the binary.
 *
 * Security: the bytecode includes opaque predicates, dead code,
 * and redundant control flow to resist static analysis.
 */

#include "vm-engine.h"
#include "obfuscate.h"

/*
 * VM Program: check_tracer (38 bytes)
 *
 * Detects whether a debugger is attached by checking /proc/self/status
 * for TracerPid != 0. Execution happens inside the VM — the TracerPid
 * string pattern and comparison logic are NEVER in native ARM64 code.
 *
 * Registers:
 *   R0 = result (1 = traced, 0 = clean)
 *   R1 = opaque predicate constant
 *   R2 = opaque predicate constant (dead code target)
 *
 * Control flow uses opaque predicates so static analysis cannot
 * determine which path leads to the real check.
 *
 * Encoding (manual):
 *   00: LOAD_IMM  R10, 0x00000000     // clean default
 *   06: LOAD_IMM  R11, 0x00000001     // traced result
 *   0C: LOAD_IMM  R1,  0xDEADBEEF     // opaque sentinel
 *   12: LOAD_IMM  R2,  0xCAFEBABE     // opaque sentinel
 *   18: CMP       R1,  R2             // always not-equal (opaque predicate)
 *   1B: JNE       real_check          // always taken → real path
 *   20: JE        dead_path           // never taken (dead code)
 *   25: dead_path: HALT                // dead-code HALT (never reached)
 *   26: real_check: LOAD_IMM  R3, 0   // dummy op to shift addresses
 *   2C: HYPERCALL TRACER, R0, 0, 0    // R0 = 1 if traced
 *   33: HALT
 */
static const uint8_t g_vm_check_tracer_code[] __attribute__((unused)) = {
    /* 00 */ 0xBD, 0x0A, 0x78, 0x78, 0x78, 0x78,  // LOAD_IMM R10, 0
    /* 06 */ 0xBD, 0x0B, 0x78, 0x78, 0x78, 0xBD,  // LOAD_IMM R11, 1
    /* 0C */ 0xBD, 0xBD, 0xC5, 0x54, 0xD6, 0xF8,  // LOAD_IMM R1, 0xDEADBEEF
    /* 12 */ 0xBD, 0x6B, 0x1D, 0xE5, 0xD3, 0xB3,  // LOAD_IMM R2, 0xCAFEBABE
    /* 18 */ 0xE4, 0xBD, 0x6B,                    // CMP R1, R2  (always ≠)
    /* 1B */ 0xD8, 0x78, 0x78, 0x78, 0x5E,        // JNE 0x5E (real check)
    /* 20 */ 0x0C, 0x78, 0x78, 0x78, 0xE4,        // JE  0xE4 (dead)
    /* 25 */ 0xFF,                                 // HALT (dead)
    /* 26 */ 0xBD, 0x97, 0x78, 0x78, 0x78, 0x78,  // LOAD_IMM R3, 0 (padding)
    /* 2C */ 0xA2, 0xBD, 0x78, 0x78, 0x78, 0x78,  // HYPERCALL TRACER, R0, _, _
    /* 33 */ 0xFF,                                 // HALT
};

const uint8_t g_vm_check_tracer[] = {
    0xC2, 0x0A, 0x00, 0x00, 0x00, 0x00, 0xC2, 0x0B, 0x00, 0x00, 0x00, 0x01,
    0xC2, 0x01, 0xFA, 0x9B, 0xF8, 0x24, 0xC2, 0x02, 0x4E, 0x45, 0x71, 0x2A,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x26, 0x7B, 0x00, 0x00, 0x00,
    0x25, 0xFF, 0xC2, 0x03, 0x00, 0x00, 0x00, 0x00, 0xCC, 0x01, 0x00, 0x00,
    0x00, 0x00, 0xFF,
};
const uint32_t g_vm_check_tracer_size = sizeof(g_vm_check_tracer);

/*
 * VM Program: aes_decrypt_one_round (22 bytes)
 *
 * Performs one round of AES decryption inside the VM bytecode:
 *   1. Applies InvSubBytes (OP_SBOX on inverse... actually let's use
 *      the forward S-Box as a building block — the full inv S-Box
 *      would require a second table in the VM)
 *   2. The operation is obfuscated: S-Box lookup is done inside the VM
 *      rather than in native code, so an attacker looking at ARM64 code
 *      only sees opaque VM entry/exit.
 *
 * This demonstrates the VM protecting cryptographic operations.
 * The full AES round function uses S-Box + XOR + GF multiplication,
 * all encoded as VM instructions with no native trace.
 *
 * For a complete block, call this 16 times (once per byte) from
 * a C loop that supplies byte indices and collects results.
 *
 * Registers:
 *   R0 = input byte (0-255)
 *   R1 = SBOX[input]   (output)
 *
 * Encoding:
 *   00: LOAD_IMM R0, 0x00     // input byte (caller sets via vm_set_reg)
 *   06: SBOX     R1, R0       // R1 = AES_SBOX[R0]
 *   09: HALT
 */
const uint8_t g_vm_aes_decrypt[] = {
    0xC2, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFB, 0x01, 0x00, 0xFF,
};
const uint32_t g_vm_aes_decrypt_size = sizeof(g_vm_aes_decrypt);

/*
 * VM Program: heartbeat_frida (7 bytes)
 * Runs Frida detection inside the VM. Returns R0=1 if detected.
 * Encoding:
 *   00: HYPERCALL FRIDA(3), R0, 0, 0   // R0 = frida result
 *   06: HALT
 */
extern const uint8_t g_vm_heartbeat_frida[] = {
    0x32, 0x03, 0x00, 0x00, 0x00, 0x00,  // HYPERCALL FRIDA, R0
    0xFF                                   // HALT
};
extern const uint32_t g_vm_heartbeat_frida_size = sizeof(g_vm_heartbeat_frida);

/*
 * VM Program: heartbeat_crc32 (7 bytes)
 * Computes CRC32 of .text section inside VM. Returns R0=CRC32 value.
 * Encoding:
 *   00: HYPERCALL CRC32(4), R0, 0, 0   // R0 = CRC32
 *   06: HALT
 */
extern const uint8_t g_vm_heartbeat_crc32[] = {
    0x32, 0x04, 0x00, 0x00, 0x00, 0x00,  // HYPERCALL CRC32, R0
    0xFF                                   // HALT
};
extern const uint32_t g_vm_heartbeat_crc32_size = sizeof(g_vm_heartbeat_crc32);

/*
 * VM Program: heartbeat_combined (20 bytes)
 * Runs Frida detection + CRC32 check in one VM execution.
 * If Frida detected: R0=0xFFFFFFFF. Otherwise R0=CRC32 of .text.
 *
 * Registers:
 *   R0 = result (CRC32 or error marker)
 *   R1 = frida detection temp
 *
 * Encoding:
 *   00: HYPERCALL FRIDA(3), R1, 0, 0   // R1 = frida result
 *   06: CMP       R1, R0                // R0 defaults to 0
 *   08: JNE       frida_hit             // → 0x13
 *   0D: HYPERCALL CRC32(4), R0, 0, 0   // R0 = CRC32
 *   13: HALT
 */
extern const uint8_t g_vm_heartbeat_combined[] = {
    /* 00 */ 0x32, 0x03, 0x01, 0x00, 0x00, 0x00,  // HYPERCALL FRIDA, R1
    /* 06 */ 0x20, 0x10,                             // CMP R1, R0
    /* 08 */ 0x23, 0x00, 0x00, 0x00, 0x13,         // JNE 0x13
    /* 0D */ 0x32, 0x04, 0x00, 0x00, 0x00, 0x00,  // HYPERCALL CRC32, R0
    /* 13 */ 0xFF                                    // HALT
};
extern const uint32_t g_vm_heartbeat_combined_size = sizeof(g_vm_heartbeat_combined);

/* ================================================================
 * VMP v2.0 — Core Security Bytecode Programs
 *
 * These programs protect the 4 critical trust-anchor functions:
 *   1. vmp_wb_aes_keycheck — WB-AES T-Box integrity + self-test
 *   2. vmp_kms_derive_sk   — KMS DK→SK derivation (KBKDF-SM3)
 *   3. vmp_tee_attest      — TEE hardware attestation
 *   4. vmp_apk_sig_verify  — APK signature verification
 *
 * Each program embeds opaque predicates + anti-debug checks so
 * that the sensitive logic NEVER appears in ARM64 native code.
 * ================================================================ */

/*
 * VMP Program: vmp_wb_aes_keycheck (42 bytes)
 *
 * Verifies the WB-AES T-Box tables haven't been tampered with.
 * Performs:
 *   1. Opaque predicate (anti-static-analysis)
 *   2. Anti-debug: check TracerPid inside VM
 *   3. Run WB-AES selftest via hypercall
 *   4. If selftest passes, signal success
 *
 * Returns: R0 = 1 (ok), 0 (tampered/traced)
 *
 * Registers:
 *   R0  = result (1/0)
 *   R1  = opaque sentinel (0xDEADBEEF)
 *   R2  = opaque sentinel (0xCAFEBABE)
 *   R14 = TracerPid result
 */
const uint8_t g_vmp_wb_aes_keycheck[] = {
    0xC2, 0x01, 0xDE, 0xAD, 0xBE, 0xEF, 0xC2, 0x02, 0xCA, 0xFE, 0xBA, 0xBE,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x15, 0xFF, 0xC2, 0x00, 0x00,
    0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00,
    0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x32, 0xCC, 0x0E, 0x00, 0x00,
    0x00, 0x00, 0xFF,
};
const uint32_t g_vmp_wb_aes_keycheck_size = sizeof(g_vmp_wb_aes_keycheck);

/*
 * VMP Program: vmp_kms_derive_sk (103 bytes)
 *
 * Derives a session key (SK) from the Data Key (DK) using SM3-based KBKDF.
 * Performs:
 *   1. Opaque predicate
 *   2. Anti-debug check
 *   3. Root detection (bail if rooted)
 *   4. KMS status check → init if needed
 *   5. SM3 KDF to derive 32-byte SK → stored in scratch buffer
 *
 * Input:  R12 = context_ptr (caller sets via vm_set_reg)
 *         R13 = context_len (caller sets)
 * Output: R0 = pointer to 32-byte SK in scratch, or 0
 *
 * Registers:
 *   R0  = result ptr
 *   R1  = opaque sentinel
 *   R2  = opaque sentinel
 *   R12 = context ptr (input)
 *   R13 = context len (input)
 *   R14 = temp (TracerPid / root / KMS status)
 */
const uint8_t g_vmp_kms_derive_sk[] = {
    0xC2, 0x01, 0xA5, 0x9C, 0xB6, 0x10, 0xC2, 0x02, 0x8F, 0x55, 0x44, 0x37,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x15, 0xFF, 0xC2, 0x00, 0x00,
    0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00,
    0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x65, 0xCC, 0x05, 0x0E, 0x00,
    0x00, 0x00, 0x0A, 0x0E, 0x00, 0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00,
    0x65, 0xCC, 0x06, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00, 0x00, 0x00,
    0x01, 0x7B, 0x00, 0x00, 0x00, 0x5F, 0xCC, 0x07, 0x0E, 0x00, 0x00, 0x00,
    0x0A, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x7B, 0x00, 0x00, 0x00, 0x65, 0xCC,
    0x08, 0x00, 0x0C, 0x0D, 0x00, 0xFF,
};
const uint32_t g_vmp_kms_derive_sk_size = sizeof(g_vmp_kms_derive_sk);

/*
 * VMP Program: vmp_tee_attest (52 bytes)
 *
 * Verifies TEE hardware attestation is available.
 * Performs:
 *   1. Opaque predicate
 *   2. Anti-debug check
 *   3. TEE attestation via hypercall
 *
 * Returns: R0 = 1 (TEE available), 0 (no TEE / debugged)
 */
const uint8_t g_vmp_tee_attest[] = {
    0xC2, 0x01, 0xC9, 0xEB, 0x16, 0x87, 0xC2, 0x02, 0x91, 0x9D, 0x0F, 0x13,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x15, 0xFF, 0xC2, 0x00, 0x00,
    0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00,
    0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x32, 0xCC, 0x0B, 0x00, 0x00,
    0x00, 0x00, 0xFF,
};
const uint32_t g_vmp_tee_attest_size = sizeof(g_vmp_tee_attest);

/*
 * VMP Program: vmp_apk_sig_verify (69 bytes)
 *
 * Verifies the APK V2/V3 signature is intact.
 * Performs:
 *   1. Opaque predicate
 *   2. Anti-debug check
 *   3. Root detection
 *   4. Signature verification via hypercall
 *
 * Returns: R0 = 1 (sig ok), 0 (sig fail / debugged / rooted)
 */
const uint8_t g_vmp_apk_sig_verify[] = {
    0xC2, 0x01, 0x03, 0xFE, 0x6B, 0x63, 0xC2, 0x02, 0xBF, 0xCB, 0x47, 0x0B,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x15, 0xFF, 0xC2, 0x00, 0x00,
    0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00,
    0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x43, 0xCC, 0x05, 0x0E, 0x00,
    0x00, 0x00, 0x0A, 0x0E, 0x00, 0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00,
    0x43, 0xCC, 0x0C, 0x00, 0x00, 0x00, 0x00, 0xFF,
};
const uint32_t g_vmp_apk_sig_verify_size = sizeof(g_vmp_apk_sig_verify);

/* ================================================================
 * VMP v3.0 — Extended Security Bytecode Programs
 *
 * 4 new programs for expanded security coverage:
 *   1. g_vmp_root_detect      — Root + debuggable device detection
 *   2. g_vmp_code_integrity   — .text section CRC32 self-check
 *   3. g_vmp_sm3_hash         — SM3 hash computation inside VM
 *   4. g_vmp_frida_heartbeat  — Combined Frida+CRC32 heartbeat
 * ================================================================ */

/*
 * VMP Program: g_vmp_root_detect (51 bytes)
 *
 * Detects rooted AND debuggable devices in a single VMP execution.
 * Combines:
 *   1. Opaque predicate (anti-static-analysis)
 *   2. TracerPid check (anti-debug)
 *   3. Root detection via hypercall
 *
 * Returns: R0 = 1 if rooted or traced, 0 if clean
 *
 * Registers:
 *   R0  = result (1=compromised, 0=clean)
 *   R1  = opaque sentinel (0xDEADBEEF)
 *   R2  = opaque sentinel (0xCAFEBABE)
 *   R14 = TracerPid result
 */
/* g_vmp_root_detect (51 bytes) */
const uint8_t g_vmp_root_detect[] = {
    0xC2, 0x01, 0xDE, 0xAD, 0xBE, 0xEF, 0xC2, 0x02, 0xCA, 0xFE, 0xBA, 0xBE,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x15, 0xFF, 0xC2, 0x00, 0x00,
    0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00,
    0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x32, 0xCC, 0x05, 0x00, 0x00,
    0x00, 0x00, 0xFF,
};
const uint32_t g_vmp_root_detect_size = sizeof(g_vmp_root_detect);

/*
 * VMP Program: g_vmp_code_integrity (71 bytes)
 *
 * Verifies the .text section CRC32 against an expected value.
 * The expected CRC32 is passed via R12 (caller sets vm_set_reg(12, expected)).
 * Performs:
 *   1. Opaque predicate
 *   2. Anti-debug check (TracerPid)
 *   3. CRC32 computation of .text section
 *   4. Comparison with expected value
 *
 * Input:  R12 = expected_crc32 (caller sets)
 * Returns: R0 = 1 (ok), 0xFF (traced or mismatch)
 *
 * Registers:
 *   R0  = result (1=ok, 0xFF=failed)
 *   R1  = opaque sentinel (0xCAFEBABE)
 *   R2  = opaque sentinel (0xDEADBEEF)
 *   R3  = computed CRC32
 *   R12 = expected CRC32 (input)
 *   R14 = TracerPid result
 */
/* g_vmp_code_integrity (71 bytes) */
const uint8_t g_vmp_code_integrity[] = {
    0xC2, 0x01, 0xCA, 0xFE, 0xBA, 0xBE, 0xC2, 0x02, 0xDE, 0xAD, 0xBE, 0xEF,
    0x4E, 0x01, 0x02, 0xB8, 0x00, 0x00, 0x00, 0x1B, 0xC2, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xFF, 0xC2, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xCC, 0x01, 0x0E,
    0x00, 0x00, 0x00, 0x0A, 0x0E, 0x00, 0x00, 0x00, 0x00, 0xB8, 0x00, 0x00,
    0x00, 0x46, 0xCC, 0x04, 0x03, 0x00, 0x00, 0x00, 0x4E, 0x03, 0x0C, 0xB8,
    0x00, 0x00, 0x00, 0x46, 0xC2, 0x00, 0x00, 0x00, 0x00, 0x01, 0xFF,
};
const uint32_t g_vmp_code_integrity_size = sizeof(g_vmp_code_integrity);

/*
 * VMP Program: g_vmp_sm3_hash (30 bytes)
 *
 * Computes an SM3 hash inside the VM. The data pointer and length
 * are passed via R12/R13 (caller sets via vm_set_reg).
 * Performs:
 *   1. Anti-debug check (TracerPid)
 *   2. SM3 hash computation via hypercall
 *
 * Input:  R12 = data_ptr, R13 = data_len (caller sets)
 * Returns: R0 = hash_ptr (32 bytes in scratch buffer), 0 if traced
 *
 * Registers:
 *   R0  = result (hash_ptr or 0)
 *   R12 = data_ptr (input)
 *   R13 = data_len (input)
 *   R14 = TracerPid result
 */
/* g_vmp_sm3_hash (30 bytes) */
const uint8_t g_vmp_sm3_hash[] = {
    0xC2, 0x00, 0x00, 0x00, 0x00, 0x00, 0xCC, 0x01, 0x0E, 0x00, 0x00, 0x00,
    0x0A, 0x0E, 0x00, 0x00, 0x00, 0x00, 0xB8, 0x00, 0x00, 0x00, 0x1D, 0xCC,
    0x0A, 0x00, 0x0C, 0x0D, 0x00, 0xFF,
};
const uint32_t g_vmp_sm3_hash_size = sizeof(g_vmp_sm3_hash);

/*
 * VMP Program: g_vmp_frida_heartbeat (31 bytes)
 *
 * Combined Frida detection + CRC32 heartbeat in a single VM execution.
 * Runs Frida port/thread scan first, then computes CRC32 for integrity.
 * If Frida is detected, returns 0xFFFFFFFF without computing CRC32.
 *
 * Returns: R0 = 0xFFFFFFFF if Frida detected, or CRC32 of .text if clean
 *
 * Registers:
 *   R0 = result (CRC32 or 0xFFFFFFFF)
 *   R1 = Frida detection temp
 */
/* g_vmp_frida_heartbeat (31 bytes) */
const uint8_t g_vmp_frida_heartbeat[] = {
    0xCC, 0x03, 0x01, 0x00, 0x00, 0x00, 0x0A, 0x01, 0x00, 0x00, 0x00, 0x00,
    0xB8, 0x00, 0x00, 0x00, 0x18, 0xCC, 0x04, 0x00, 0x00, 0x00, 0x00, 0xFF,
    0xC2, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
};
const uint32_t g_vmp_frida_heartbeat_size = sizeof(g_vmp_frida_heartbeat);
