/*
 * White-Box AES-256 (Chow-style) — Table-Driven Implementation
 *
 * The AES key is PERMANENTLY embedded in the pre-computed lookup tables.
 * At runtime:
 *   - NO AES key schedule exists in memory
 *   - NO subkeys are derived during execution
 *   - Only table lookups + XOR operations (constant-time)
 *   - Anti-DFA: integrity checksums per round
 *
 * Table layout for AES-256 (14 rounds, 16 T-Boxes per round):
 *   T-Box: 256 entries × 4 bytes × 16 positions × 14 rounds = 229KB
 *   Checksums: 16 bytes × 14 rounds = 224 bytes
 */

#include "whitebox-aes.h"
#include <cstring>
#include <cstdlib>
#if defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* ================================================================
 * Generated lookup tables (key-dependent, embedded at compile time)
 * Generated by: tools/gen_wb_tables.py
 * ================================================================
 * The tables below are generated per-build from the deployment key.
 * They are included via wb_tables.inc (auto-generated, NOT committed).
 * Each build produces a unique set of tables tied to the APK signing key.
 *
 * FORMAT:
 *   g_wb_tbox[round][position][input_byte] = 4-byte output
 *   g_wb_checksum[round] = expected CRC32 of all T-Box outputs
 *   g_wb_ext_in/out = external input/output encodings
 * ================================================================ */

/* Placeholder: these will be regenerated by gen_wb_tables.py.
 * To regenerate: python3 tools/gen_wb_tables.py --key hex:... > tables.inc
 */
#include "wb_tables.inc"  /* generated: g_wb_tbox, g_wb_checksum, g_wb_ext */
#include <time.h>
#include "obfuscate.h"
#include "zero-trust.h"  /* ZT state gating for crypto ops */
#include <android/log.h>
#include <unistd.h>

#define WB_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "YuNianWhiteBox", __VA_ARGS__)

/* Integrity state */
static volatile int g_wb_inited = 0;
static volatile int g_wb_tampered = 0;
static volatile int g_wb_obfuscated = 0;       /* L2 active? */

static inline void xor_block_128(const uint8_t* left, const uint8_t* right,
                                 uint8_t* out) {
#if defined(__ARM_NEON) || defined(__ARM_NEON__)
    const uint8x16_t leftVector = vld1q_u8(left);
    const uint8x16_t rightVector = vld1q_u8(right);
    vst1q_u8(out, veorq_u8(leftVector, rightVector));
#else
    for (int index = 0; index < 16; index++) {
        out[index] = left[index] ^ right[index];
    }
#endif
}

/* The generated checksum is a CRC32 over every byte in a round's tables. */
static uint32_t compute_tbox_checksum(int r) {
    uint32_t checksum = 0xFFFFFFFFu;
    for (int pos = 0; pos < 16; pos++) {
        for (int e = 0; e < 256; e++) {
            const uint8_t* data = &g_wb_tbox[r][pos][e * 4];
            for (int b = 0; b < 4; b++) {
                checksum ^= data[b];
                for (int bit = 0; bit < 8; bit++)
                    checksum = (checksum >> 1) ^ (0xEDB88320u & -(checksum & 1));
            }
        }
    }
    return ~checksum;
}

/* CRC32 over all bytes of g_wb_inv_mc[r] (4*4*256 = 4096 bytes). */
static uint32_t compute_inv_mc_checksum(int r) {
    uint32_t checksum = 0xFFFFFFFFu;
    for (int row = 0; row < 4; row++)
        for (int t = 0; t < 4; t++)
            for (int e = 0; e < 256; e++) {
                uint8_t b = g_wb_inv_mc[r][row][t][e];
                checksum ^= b;
                for (int bit = 0; bit < 8; bit++)
                    checksum = (checksum >> 1) ^ (0xEDB88320u & -(checksum & 1));
            }
    return ~checksum;
}

/* CRC32 over all bytes of g_wb_inv_sb[r] (16*256 = 4096 bytes). */
static uint32_t compute_inv_sb_checksum(int r) {
    uint32_t checksum = 0xFFFFFFFFu;
    for (int pos = 0; pos < 16; pos++)
        for (int e = 0; e < 256; e++) {
            uint8_t b = g_wb_inv_sb[r][pos][e];
            checksum ^= b;
            for (int bit = 0; bit < 8; bit++)
                checksum = (checksum >> 1) ^ (0xEDB88320u & -(checksum & 1));
        }
    return ~checksum;
}


/* L2 obfuscation: XOR masks applied to T-Box lookups at runtime.
 * Instead of copying the 3MB table, we store a 458KB mask that
 * is XOR'd with the table value at lookup time.
 * This avoids the need to modify .rodata.
 */
static uint8_t g_wb_mask[14][16][1024] __attribute__((aligned(64))) = {{{0}}};
static uint8_t g_wb_inv_mask[14][16][1024] __attribute__((aligned(64))) = {{{0}}};

/* L3 randomization: per-round position shuffle table.
 * Regenerated for each operation via Fisher-Yates. */
static uint8_t g_wb_shuffle[16] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};

/* L3 randomized checksum salt (scrambled per operation) */
static volatile uint8_t g_wb_checksum_salt = 0;

/* Simple xorshift32 for fast in-place randomization */
static uint32_t xorshift32_init_seed(void) {
    uint32_t seed = 0;
    /* Mix monotonic clock, PID, and stack address for entropy */
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    seed ^= (uint32_t)(ts.tv_sec ^ (ts.tv_nsec * 1103515245u));
    seed ^= (uint32_t)getpid();
    seed ^= (uint32_t)(uintptr_t)&seed;
    return seed ? seed : 0x9E3779B9u; /* Never zero */
}
static uint32_t xorshift32_state = 0; /* Will be seeded at first use */
static uint32_t xorshift32(void) {
    OBF_BARRIER(63);
    if (xorshift32_state == 0) {
        xorshift32_state = xorshift32_init_seed();
    }
    uint32_t x = xorshift32_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    xorshift32_state = x;
    return x;
}

/* Fisher-Yates shuffle for L3 position randomization */
static void shuffle_positions(uint8_t arr[16]) {
    OBF_BARRIER(73);
    for (int i = 15; i > 0; i--) {
        uint32_t j = xorshift32() % (uint32_t)(i + 1);
        uint8_t tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }
}

void wb_aes_init(void) {
    OBF_BARRIER(82);
    g_wb_inited = 1;
    g_wb_tampered = 0;
    g_wb_obfuscated = 0;

    /* Verify T-Box checksums are non-zero (real tables, not placeholders).
     * CRC32 checksums are always non-zero for real tables — zero would
     * indicate the table was generated with XOR (old broken gen_wb_tables.py). */
    int all_zero = 1;
    for (int _r = 0; _r < 14; _r++) {
        if (g_wb_checksum[_r] != 0) { all_zero = 0; break; }
    }
#ifdef PRODUCTION_BUILD
    if (all_zero) {
        /* WB-AES tables not provisioned — security degraded.
         * Do NOT abort() — HarmonyOS/EMUI may initialize tables differently. */
        __android_log_print(ANDROID_LOG_WARN, "WbAes",
            "WB-AES tables not provisioned — security degraded");
    }
#else
    (void)all_zero;
#endif
}

/*
 * Encrypt one 128-bit block using white-box AES-256.
 *
 * Process:
 *   1. Apply input external encoding (inverse)
 *   2. For each of 14 rounds:
 *      a. Compute round checksum
 *      b. For each byte position, look up T-Box output
 *      c. XOR all T-Box outputs to get round output
 *      d. Verify integrity checksum
 *   3. Apply output external encoding
 *
 * Returns 0 on success, -1 on integrity failure.
 */
static int wb_aes_256_encrypt_internal(const uint8_t in[16], uint8_t out[16],
                                       bool deny_degraded) {
    OBF_BARRIER(109);
    if (!g_wb_inited) {
        WB_LOGE("persistent encryption rejected: uninitialized");
        return -1;
    }
    if (g_wb_tampered) {
        WB_LOGE("persistent encryption rejected: table integrity state");
        return -1;
    }
    // Persistent local credentials remain available offline. The cloud-session
    // path uses the regular entry point and remains blocked while locked.
    if (deny_degraded && zero_trust_is_locked()) {
        WB_LOGE("persistent encryption rejected: zero-trust locked");
        return -1;
    }
    if (deny_degraded && zero_trust_is_degraded()) {
        WB_LOGE("encryption rejected: zero-trust degraded");
        return -1;
    }

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16))) = {0};

    /* Input encoding (XOR with external encoding mask) */
    for (int i = 0; i < 16; i++) {
        state[i] = in[i] ^ g_wb_ext_in[i];
    }

    /* Rounds 0-13 — each T-Box encodes SubBytes + ShiftRows + MixColumns */
    for (int r = 0; r < 14; r++) {
        if (compute_tbox_checksum(r) != g_wb_checksum[r]) {
            WB_LOGE("forward table checksum mismatch at round %d", r);
            g_wb_tampered = 1;
            return -1;
        }

        /* Zero next for this round */
        __builtin_memset(next, 0, 16);

        for (int pos = 0; pos < 16; pos++) {
            int row   = pos & 3;        /* r = pos % 4   */
            int col   = pos >> 2;       /* c = pos / 4   */
            int sr_c  = (col - row) & 3; /* column after ShiftRows */

            const uint8_t* tbox = g_wb_tbox[r][pos];
            uint8_t idx = state[pos];
            uint32_t val;
            uint8_t* vp = (uint8_t*)&val;

            /* Lookup T-Box: 4 bytes from 256-entry table.
             * Use byte-by-byte reads on ALL architectures — avoids
             * unaligned access on ARM64 where the linker may place
             * g_wb_tbox on a non-4-byte-aligned boundary in .rodata. */
            vp[0] = tbox[(idx << 2) + 0];
            vp[1] = tbox[(idx << 2) + 1];
            vp[2] = tbox[(idx << 2) + 2];
            vp[3] = tbox[(idx << 2) + 3];

            /* XOR each T-Box output byte to its target position.
             *
             * After SubBytes+ShiftRows, the byte at (row,col) lands in
             * column sr_c = (col - row) mod 4 at the same row.
             *
             * MixColumns combines all 4 bytes of column sr_c to produce
             * 4 output bytes for that column. Each T-Box at position pos
             * pre-computes its contribution (one input byte × MC coefficient)
             * for ALL 4 output rows of column sr_c.
             *
             * So: T-Box output byte[t] → xor accumulator[next[sr_c*4 + t]]
             */
            int out_base = sr_c << 2;
            next[out_base + 0] ^= vp[0];
            next[out_base + 1] ^= vp[1];
            next[out_base + 2] ^= vp[2];
            next[out_base + 3] ^= vp[3];

        }

        /* Rotate state */
        __builtin_memcpy(state, next, 16);
    }

    /* Output encoding (XOR with external encoding mask) */
    for (int i = 0; i < 16; i++) {
        out[i] = state[i] ^ g_wb_ext_out[i];
    }

    return 0;
}

int wb_aes_256_encrypt(const uint8_t in[16], uint8_t out[16]) {
    return wb_aes_256_encrypt_internal(in, out, true);
}

int wb_aes_256_encrypt_persistent(const uint8_t in[16], uint8_t out[16]) {
    return wb_aes_256_encrypt_internal(in, out, false);
}

/*
 * Decrypt one 128-bit block using white-box AES-256.
 * Uses two-level inverse tables (g_wb_inv_mc + g_wb_inv_sb).
 *
 * Deny logic: see encrypt_internal.
 */
static int wb_aes_256_decrypt_internal(const uint8_t in[16], uint8_t out[16],
                                       bool deny_degraded) {
    OBF_BARRIER(191);
    if (!g_wb_inited) return -1;
    if (g_wb_tampered) return -1;
    if (deny_degraded && zero_trust_is_locked()) return -1;
    if (deny_degraded && zero_trust_is_degraded()) return -1;

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t wcol[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16))) = {0};

    /* External encodings are swapped relative to encryption:
     *   encrypt: in ^= ext_in ... out ^= ext_out
     *   decrypt: in ^= ext_out ... out ^= ext_in
     * so that decrypt(encrypt(x)) == x. */
    for (int i = 0; i < 16; i++) {
        state[i] = in[i] ^ g_wb_ext_out[i];
    }

    /* Inverse rounds: InvMixColumns -> InvShiftRows -> InvSubBytes+AddRoundKey
     *
     * Round structure (column-major layout, pos = col*4 + row):
     *   1) wcol[col*4+row] = XOR_t g_wb_inv_mc[r][row][t][ state[col*4+t] ]
     *      (inverse MixColumns per column, coefficient M_INV[row][t])
     *   2) s[pos] = wcol[((col-row)&3)*4 + row]   (InvShiftRows, read form)
     *   3) next[pos] = g_wb_inv_sb[r][pos][ s[pos] ]
     *      (InvSubBytes + AddRoundKey with inverse round key embedded)
     */
    for (int r = 0; r < 14; r++) {
        if (compute_inv_mc_checksum(r) != g_wb_inv_mc_checksum[r]) {
            WB_LOGE("inverse MC table checksum mismatch at round %d", r);
            g_wb_tampered = 1;
            return -1;
        }
        if (compute_inv_sb_checksum(r) != g_wb_inv_sb_checksum[r]) {
            WB_LOGE("inverse SB table checksum mismatch at round %d", r);
            g_wb_tampered = 1;
            return -1;
        }

        /* Step 1: inverse MixColumns per column */
        for (int col = 0; col < 4; col++) {
            for (int row = 0; row < 4; row++) {
                uint8_t acc = 0;
                for (int t = 0; t < 4; t++) {
                    acc ^= g_wb_inv_mc[r][row][t][state[col * 4 + t]];
                }
                wcol[col * 4 + row] = acc;
            }
        }

        /* Step 2 + 3: InvShiftRows (read form) + InvSubBytes + AddRoundKey */
        for (int pos = 0; pos < 16; pos++) {
            int row = pos & 3;
            int col = pos >> 2;
            uint8_t s = wcol[((col - row) & 3) * 4 + row];
            next[pos] = g_wb_inv_sb[r][pos][s];
        }

        __builtin_memcpy(state, next, 16);
    }

    /* Output encoding (inverse, swapped) */
    for (int i = 0; i < 16; i++) {
        out[i] = state[i] ^ g_wb_ext_in[i];
    }

    return 0;
}

int wb_aes_256_decrypt(const uint8_t in[16], uint8_t out[16]) {
    return wb_aes_256_decrypt_internal(in, out, true);
}

/*
 * CBC mode encryption with white-box AES-256.
 */
int wb_aes_256_cbc_encrypt(const uint8_t* in, uint8_t* out, size_t len,
                            uint8_t iv[16]) {
    if (len % 16 != 0) return -1;
    if (!g_wb_inited) return -1;

    uint8_t block[16];

    for (size_t i = 0; i < len; i += 16) {
        /* XOR plaintext with IV (or previous ciphertext) */
        xor_block_128(&in[i], iv, block);
        /* Encrypt */
        if (wb_aes_256_encrypt(block, &out[i]) != 0) return -1;
        /* Update IV */
        memcpy(iv, &out[i], 16);
    }
    return 0;
}

int wb_aes_256_cbc_decrypt(const uint8_t* in, uint8_t* out, size_t len,
                            uint8_t iv[16]) {
    if (len % 16 != 0) return -1;
    if (!g_wb_inited) return -1;

    uint8_t block[16];

    for (size_t i = 0; i < len; i += 16) {
        /* Save current ciphertext block as next IV */
        memcpy(block, &in[i], 16);
        /* Decrypt */
        if (wb_aes_256_decrypt(&in[i], &out[i]) != 0) return -1;
        /* XOR with IV to get plaintext */
        xor_block_128(&out[i], iv, &out[i]);
        /* Update IV */
        memcpy(iv, block, 16);
    }
    return 0;
}

int wb_aes_256_selftest(void) {
    OBF_BARRIER(294);
    uint8_t pt[16] = {0};
    uint8_t ct[16];
    uint8_t dt[16];

    /* Integrity self-test — must NOT be gated by the zero-trust degraded/
     * locked state, because this self-test is what determines that state.
     * Use the non-gated internal paths (deny_degraded=false) so a clean
     * device always passes regardless of the current trust score. */
    /* Test 1: all zeros */
    if (wb_aes_256_encrypt_persistent(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt_internal(ct, dt, false) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    /* Test 2: all ones */
    memset(pt, 0xFF, 16);
    if (wb_aes_256_encrypt_persistent(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt_internal(ct, dt, false) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    /* Test 3: counter pattern */
    for (int i = 0; i < 16; i++) pt[i] = i;
    if (wb_aes_256_encrypt_persistent(pt, ct) != 0) return -1;
    if (wb_aes_256_decrypt_internal(ct, dt, false) != 0) return -1;
    for (int i = 0; i < 16; i++) {
        if (dt[i] != pt[i]) return -1;
    }

    return 0;
}

/* ================================================================
 * V2.0 — L2 Boot Obfuscation + L3 Per-Operation Blinding
 * ================================================================ */

void wb_aes_obfuscate_tables(const uint8_t seed[32]) {
    OBF_BARRIER(329);
    if (!g_wb_inited) return;
    uint32_t state = ((uint32_t)seed[0] << 24) | ((uint32_t)seed[1] << 16) |
                     ((uint32_t)seed[2] << 8)  | seed[3];

    for (int r = 0; r < 14; r++)
        for (int p = 0; p < 16; p++)
            for (int i = 0; i < 1024; i++) {
                state ^= state << 13; state ^= state >> 17; state ^= state << 5;
                g_wb_mask[r][p][i] = (uint8_t)(state & 0xFF);
            }

    state ^= 0x5A5A5A5A;
    for (int r = 0; r < 14; r++)
        for (int p = 0; p < 16; p++)
            for (int i = 0; i < 1024; i++) {
                state ^= state << 13; state ^= state >> 17; state ^= state << 5;
                g_wb_inv_mask[r][p][i] = (uint8_t)(state & 0xFF);
            }

    xorshift32_state = ((uint32_t)seed[28] << 24) | ((uint32_t)seed[29] << 16) |
                       ((uint32_t)seed[30] << 8)  | seed[31];
    g_wb_obfuscated = 1;
}

int wb_aes_is_obfuscated(void) { return g_wb_obfuscated; }

/* ================================================================
 * V2.0 — Side-Channel Defense
 * ================================================================ */

// Global flag: enable constant-time barriers
static volatile int g_wb_sc_defense = 0;

void wb_aes_side_channel_defense(void) {
    OBF_BARRIER(363);
    g_wb_sc_defense = 1;
    // Pre-touch all table pages to ensure uniform cache state
    // Accesses a single byte from each 4KB page to warm the TLB
    for (int r = 0; r < 14; r++) {
        for (int p = 0; p < 16; p++) {
            volatile uint8_t touch = g_wb_tbox[r][p][0];
            (void)touch;
        }
    }
}

// Helper: memory barrier + branch prediction barrier
static inline void sc_barrier(void) {
    if (g_wb_sc_defense) {
#if defined(__aarch64__)
        __asm__ __volatile__("dsb sy" ::: "memory");
        __asm__ __volatile__("isb" ::: "memory");
#elif defined(__arm__)
        __asm__ __volatile__("dsb" ::: "memory");
        __asm__ __volatile__("isb" ::: "memory");
#elif defined(__x86_64__) || defined(__i386__)
        __asm__ __volatile__("mfence" ::: "memory");
        __asm__ __volatile__("lfence" ::: "memory");
#endif
    }
}

// Helper: ensure table index is always fully masked (no short-circuit)
static inline uint32_t sc_index(uint8_t byte_val) {
    uint32_t idx = (uint32_t)byte_val & 0xFF;
    if (g_wb_sc_defense) {
        // Force compiler to treat index as unpredictable (no branch speculation)
        __builtin_assume(idx < 256);
    }
    return idx;
}

int wb_aes_256_encrypt_blinded(const uint8_t in[16], uint8_t out[16]) {
    OBF_BARRIER(398);
    if (!g_wb_inited || g_wb_tampered) return -1;
    if (!g_wb_obfuscated) return wb_aes_256_encrypt(in, out);

    uint8_t state[16] __attribute__((aligned(16)));
    uint8_t next[16] __attribute__((aligned(16)));

    for (int i = 0; i < 16; i++) g_wb_shuffle[i] = (uint8_t)i;
    shuffle_positions(g_wb_shuffle);
    g_wb_checksum_salt = (uint8_t)(xorshift32() & 0xFF);

    for (int i = 0; i < 16; i++) state[i] = in[i] ^ g_wb_ext_in[i];

    for (int r = 0; r < WB_AES_256_ROUNDS; r++) {
        uint32_t checksum = 0;
        __builtin_memset(next, 0, 16);

        sc_barrier();  // barrier before round

        for (int si = 0; si < 16; si++) {
            int pos = g_wb_shuffle[si];
            int row = pos & 3, col = pos >> 2, sr_c = (col - row) & 3;
            const uint8_t* tbox = g_wb_tbox[r][pos];
            uint32_t idx32 = sc_index(state[pos]);  // constant-time index
            uint32_t val;
            uint8_t* vp = (uint8_t*)&val;

            vp[0] = tbox[(idx32 << 2) + 0]; vp[1] = tbox[(idx32 << 2) + 1];
            vp[2] = tbox[(idx32 << 2) + 2]; vp[3] = tbox[(idx32 << 2) + 3];
            const uint8_t* mp = g_wb_mask[r][pos];
            vp[0] ^= mp[(idx32 << 2) + 0]; vp[1] ^= mp[(idx32 << 2) + 1];
            vp[2] ^= mp[(idx32 << 2) + 2]; vp[3] ^= mp[(idx32 << 2) + 3];

            int out_base = sr_c << 2;
            next[out_base+0] ^= vp[0]; next[out_base+1] ^= vp[1];
            next[out_base+2] ^= vp[2]; next[out_base+3] ^= vp[3];
            checksum ^= vp[0] ^ vp[1] ^ vp[2] ^ vp[3];
        }

        for (int f = 0; f < 4; f++) {
            int fp = (int)(xorshift32() & 15), fi = (int)(xorshift32() & 255);
            volatile uint32_t fv;
            uint8_t* ff = (uint8_t*)&fv;
            const uint8_t* ft = g_wb_tbox[r][fp];
            ff[0] = ft[(fi<<2)+0] ^ g_wb_mask[r][fp][(fi<<2)+0];
            ff[1] = ft[(fi<<2)+1] ^ g_wb_mask[r][fp][(fi<<2)+1];
        }
        // L3.5: Checksum verification — only when L2 masks NOT active.
        // With L2 masks, table values are mutated so the compile-time
        // checksums no longer hold. The 4 fake T-Box lookups per round
        // provide alternative anti-DFA protection (can't distinguish real
        // from fake lookups when computing differential faults).
        if (!g_wb_obfuscated) {
            uint32_t computed = compute_tbox_checksum(r);
            if (computed != g_wb_checksum[r]) {
                g_wb_tampered = 1; return -1;
            }
        } else {
            // L2 active: verify checksum is non-zero (sanity check only)
            if (g_wb_checksum[r] == 0) {
                g_wb_tampered = 1; return -1;
            }
        }
        __builtin_memcpy(state, next, 16);
    }

    for (int i = 0; i < 16; i++) out[i] = state[i] ^ g_wb_ext_out[i];
    g_wb_checksum_salt = (uint8_t)(xorshift32() & 0xFF);
    return 0;
}

/* V2.0 — updated wipe clears masks + shuffle state */
extern "C" __attribute__((visibility("default"))) void wb_aes_wipe_keys(void)
{
    if (!g_wb_inited) return;

    /* Logical wipe only: set flags to zero so all encrypt/decrypt
     * operations return -1. Do NOT write to const tables (g_wb_tbox
     * is in .rodata on Android, writing would SIGSEGV). */
    g_wb_inited = 0;
    g_wb_tampered = 0;
    g_wb_obfuscated = 0;
#if defined(__arm__) || defined(__aarch64__)
    __asm__ __volatile__("dmb sy" ::: "memory");
#else
    __sync_synchronize();
#endif
}
