#!/usr/bin/env python3
"""
embed_payload.py — Embed encrypted DEX via objcopy (no C compiler involved)

1. Reads APK, extracts classes.dex
2. SM4-ECB encrypts (via compiled C helper)
3. For each ABI, creates a linkable .o file via objcopy
4. Writes a thin g_vmp_payload_data.cpp referencing the embedded symbols
5. The .o files are added to Android.mk as LOCAL_LDFLAGS extras

Requires: objcopy (from binutils), gcc (for SM4 helper)
"""

import os, sys, struct, zlib, zipfile, subprocess, argparse

ABI_TARGETS = {
    'arm64-v8a':   'elf64-littleaarch64',
    'armeabi-v7a': 'elf32-littlearm',
    'x86_64':      'elf64-x86-64',
    'x86':         'elf32-i386',
}

OBJCOPY = '/opt/android-sdk/ndk/30.0.14904198/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objcopy'

SM4_HELPER = '/tmp/sm4_fast_enc'

def sm4_encrypt(plaintext, key_bytes):
    """Encrypt using compiled C SM4 helper."""
    import tempfile
    with tempfile.NamedTemporaryFile(suffix='.bin', delete=False) as f:
        f.write(plaintext); plain_path = f.name
    enc_path = plain_path + '.enc'
    subprocess.run([SM4_HELPER, 'enc', plain_path, enc_path, key_bytes.hex()],
                   check=True, capture_output=True)
    with open(enc_path, 'rb') as f:
        encrypted = f.read()
    os.unlink(plain_path); os.unlink(enc_path)
    return encrypted

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--apk', required=True)
    parser.add_argument('--payload-dir', required=True, help='e.g. core/security/src/main/cpp/payload')
    parser.add_argument('--cpp-out', required=True, help='g_vmp_payload_data.cpp output')
    args = parser.parse_args()

    # 1. Extract DEX
    with zipfile.ZipFile(args.apk, 'r') as zf:
        dex_data = zf.read('classes.dex')
    print(f'📦 DEX: {len(dex_data)} bytes')

    # 2. Pad to 16B
    pad = (16 - len(dex_data) % 16) % 16
    if pad: dex_data += b'\x00' * pad
    original_len = len(dex_data)

    # 3. SM4 key + encrypt + CRC32
    key = os.urandom(16)
    encrypted = sm4_encrypt(dex_data, key)
    crc32_val = zlib.crc32(dex_data) & 0xFFFFFFFF
    print(f'🔑 Key: {key.hex()}  CRC32: 0x{crc32_val:08X}  Encrypted: {len(encrypted)} bytes')

    # 4. XOR-obfuscate key
    seed = struct.pack('<I', 0x9E3A7C51)
    obf = bytes([(key[i] ^ seed[i % 4] ^ (i * 0x5D)) & 0xFF for i in range(16)])

    # 5. Save encrypted binary
    bin_path = os.path.join(args.payload_dir, 'vmp_payload.bin')
    os.makedirs(args.payload_dir, exist_ok=True)
    with open(bin_path, 'wb') as f:
        f.write(encrypted)

    # 6. Create .o files per ABI
    for abi, elf_fmt in ABI_TARGETS.items():
        abi_dir = os.path.join(args.payload_dir, abi)
        os.makedirs(abi_dir, exist_ok=True)
        obj_path = os.path.join(abi_dir, 'vmp_payload.o')
        # Run objcopy from the bin's directory so symbols are short
        # (e.g. _binary_vmp_payload_bin_start) instead of embedding
        # the full relative path in the symbol name.
        bin_dir = os.path.dirname(bin_path)
        bin_name = os.path.basename(bin_path)
        # obj_path must be absolute (or relative to cwd=bin_dir)
        abs_obj_path = os.path.abspath(obj_path)
        subprocess.run([
            OBJCOPY, '-I', 'binary', '-O', elf_fmt,
            '--rename-section', '.data=.rodata,alloc,load,readonly,data,contents',
            bin_name, abs_obj_path
        ], check=True, cwd=bin_dir)
        sz = os.path.getsize(obj_path)
        print(f'  {abi}: {sz} bytes → {obj_path}')

    # 7. Write thin C++ file (only key + CRC + extern symbols)
    with open(args.cpp_out, 'w') as f:
        f.write(f'''/*
 * AUTO-GENERATED by tools/embed_payload.py
 * Encrypted DEX embedded via objcopy — no C array needed.
 */
#include "dex-packer.h"

/* XOR-obfuscated SM4 key */
const uint8_t g_vmp_sm4_key[16] = {{{', '.join(f'0x{b:02X}' for b in obf)}}};

/* CRC32 of decrypted payload (verified at runtime) */
const uint32_t g_vmp_payload_crc32 = 0x{crc32_val:08X}U;

/* Symbols provided by vmp_payload.o (objcopy -I binary).
 * Use _start + _end (both RELATIVE symbols) to compute size,
 * avoiding the ABSOLUTE _size symbol that breaks ARM64 ADRP relocs. */
extern "C" {{
    extern const char _binary_vmp_payload_bin_start __attribute__((visibility("hidden")));
    extern const char _binary_vmp_payload_bin_end   __attribute__((visibility("hidden")));
}}

const uint8_t* g_vmp_payload = (const uint8_t*)&_binary_vmp_payload_bin_start;
const uint32_t g_vmp_payload_size = (uint32_t)((uintptr_t)&_binary_vmp_payload_bin_end - (uintptr_t)&_binary_vmp_payload_bin_start);
''')
    print(f'✅ {args.cpp_out} written')

    print(f'\n📋 Next: add to Android.mk LOCAL_LDFLAGS:')
    print(f'   LOCAL_LDFLAGS += $(LOCAL_PATH)/payload/$(TARGET_ARCH_ABI)/vmp_payload.o')


if __name__ == '__main__':
    main()
