#!/usr/bin/env python3
"""
Generate g_vmp_payload_data.cpp + g_vmp_config.h from encrypted business DEX + SM4 key.

Each build gets randomized algorithm constants:
  - LCG multiplier & addend (scatter algorithm)
  - XOR multiplier (key deobfuscation formula)
  Written to g_vmp_config.h, consumed by dex-packer.cpp at compile time.

Usage:
  python3 gen_payload_cpp.py <encrypted_dex> <output_cpp> <crc32_hex> <sm4_key_hex> <seed_hex>
"""

import sys
import os
import random
from pathlib import Path


def random_odd_u32() -> int:
    """Random 32-bit odd integer (LCG requires odd multiplier for full period)."""
    return (random.randint(1, 0x7FFFFFFF) * 2 + 1) & 0xFFFFFFFF


def compute_obfuscated_key(actual_key_hex: str, xor_key_seed: int,
                           xor_mult: int, xor_stride: int) -> bytes:
    """Reverse deobfuscate_key() to produce the stored obfuscated key.
    Uses randomized constants from config. """
    actual_key = bytes.fromhex(actual_key_hex)
    seed = [
        (xor_key_seed >> 0) & 0xFF,
        (xor_key_seed >> 8) & 0xFF,
        (xor_key_seed >> 16) & 0xFF,
        (xor_key_seed >> 24) & 0xFF,
    ]
    obf = bytearray(16)
    for i in range(16):
        stride = (i * xor_stride) & 3
        mul = (i * xor_mult) & 0xFF
        obf[i] = actual_key[i] ^ seed[stride] ^ mul
    return bytes(obf)


def scatter_key_positions(seed: int, lcg_mul: int, lcg_add: int) -> list:
    """Derive 16 unique positions using randomized LCG constants."""
    positions = []
    state = seed
    for _ in range(16):
        state = (state * lcg_mul + lcg_add) & 0xFFFFFFFF
        pos = state % 240
        while pos in positions:
            pos = (pos + 1) % 240
        positions.append(pos)
    return positions


def generate_shell_names() -> dict:
    """Generate randomized Java identifiers for shell method/field names.
    Returns a dict keyed by logical name → random Java identifier.
    Each build gets different names, making static string-search useless."""
    import string as _s
    def random_java_id():
        # Valid Java identifier: starts with letter/underscore/$, alphanumeric thereafter
        prefix = random.choice('_abcdef')
        body = ''.join(random.choices(_s.ascii_letters + _s.digits, k=random.randint(10, 16)))
        return prefix + body

    names = {
        'load_payload':   random_java_id(),  # nativeLoadPayload replacement
        'dex_classloader': random_java_id(),  # sDexClassLoader field
        'real_app_class':  random_java_id(),  # sRealAppClass field
    }
    print(f"   Shell names: load_payload={names['load_payload']} "
          f"dex_cl={names['dex_classloader']} real_app={names['real_app_class']}",
          file=sys.stderr)
    return names


def generate_config(cpp_dir: Path, lcg_mul: int, lcg_add: int,
                    xor_mult: int, xor_stride: int,
                    integrity_mul: int, seed: int,
                    shell_names: dict = None) -> None:
    """Write g_vmp_config.h — consumed by dex-packer.cpp and native-bridge.cpp."""
    mask_val = xor_stride - 1  # xor_stride is always 2, 4, or 8
    # Shell name macros (empty if not provided)
    shell_macros = ""
    if shell_names:
        shell_macros = f'''
// ── Shell method/field name obfuscation (per-build random) ─────────
// These replace the hardcoded JNI names in Kotlin shell + C++ gMethods.
// C++:  RegisterNatives with VMP_SHELL_LOAD_PAYLOAD instead of "nativeLoadPayload"
//       GetStaticFieldID with VMP_SHELL_DEX_LOADER instead of "sDexClassLoader"
//       GetStaticFieldID with VMP_SHELL_REAL_APP_CLASS instead of "sRealAppClass"
// Kotlin: external fun {shell_names['load_payload']}(...) replaces nativeLoadPayload
//         @JvmStatic var {shell_names['dex_classloader']} replaces sDexClassLoader
//         @JvmStatic var {shell_names['real_app_class']} replaces sRealAppClass
#define VMP_SHELL_LOAD_PAYLOAD   "{shell_names['load_payload']}"
#define VMP_SHELL_DEX_LOADER     "{shell_names['dex_classloader']}"
#define VMP_SHELL_REAL_APP_CLASS "{shell_names['real_app_class']}"
'''
    content = f'''// Auto-generated per-build VMP configuration — DO NOT COMMIT
// Each APK build gets randomized algorithm constants.
// Generated by gen_payload_cpp.py at build time.

#ifndef YUNIAN_VMP_CONFIG_H
#define YUNIAN_VMP_CONFIG_H

#include <stdint.h>

// ── LCG parameters for scatter_key_positions ──────────────────────
// state = (state * VMP_LCG_MUL + VMP_LCG_ADD) & 0xFFFFFFFF
#define VMP_LCG_MUL  0x{lcg_mul:08X}u
#define VMP_LCG_ADD  0x{lcg_add:08X}u

// ── XOR deobfuscation parameters for deobfuscate_key ──────────────
// key_out[i] = obf_key[i] ^ seed[(i * VMP_XOR_STRIDE) & 3] ^ (i * VMP_XOR_MULT)
#define VMP_XOR_MULT    0x{xor_mult:02X}u
#define VMP_XOR_STRIDE  0x{xor_stride:02X}u

// ── Integrity seed multiplier (vm-engine.cpp vm_init) ─────────────
// Replaces hardcoded 1103515245 with per-build random value.
#define VMP_INTEGRITY_MUL  0x{integrity_mul:08X}u

// ── Seed (cert CRC32, for reference only — not used at runtime) ───
#define VMP_BUILD_SEED  0x{seed:08X}u
{shell_macros}
#endif // YUNIAN_VMP_CONFIG_H
'''
    config_path = cpp_dir / "g_vmp_config.h"
    with open(config_path, 'w') as f:
        f.write(content)
    print(f"   Config: {config_path} ({len(content)} bytes)", file=sys.stderr)
    print(f"   LCG: mul=0x{lcg_mul:08X} add=0x{lcg_add:08X}", file=sys.stderr)
    print(f"   XOR: mult=0x{xor_mult:02X} stride=0x{xor_stride:02X}", file=sys.stderr)

    # Also write shell names as JSON for build_shell_apk.py to read
    if shell_names:
        import json as _json
        names_path = cpp_dir / "g_vmp_shell_names.json"
        with open(names_path, 'w') as f:
            _json.dump(shell_names, f)
        print(f"   Shell names → {names_path}", file=sys.stderr)


# ── Secure String Table ──────────────────────────────────────────────

SS_STRINGS = [
    "api.lianyu.app",           # 0
    "/v1/sync",                 # 1
    "https://api.github.com",   # 2
    "linruoxi666",              # 3
    "LianYu",                   # 4
    "lianyu://oauth/callback",  # 5
    "https://api.openai.com/v1/",       # 6
    "https://api.deepseek.com/v1/",     # 7
    "https://dashscope.aliyuncs.com/compatible-mode/v1/",  # 8
    "https://api.moonshot.cn/v1/",      # 9
    "https://api.anthropic.com/v1/",    # 10
    "https://generativelanguage.googleapis.com/v1beta/openai/",  # 11
    "com.yunian.ai.security.SecurityProvider",  # 12
    "/chat/completions",        # 13
    "/messages",                # 14
    "chat/completions",         # 15
    "messages",                 # 16
    "https://api.xiaomimimo.com/v1/",    # 17
    "https://open.bigmodel.cn/api/paas/v4/",  # 18
    "https://api.siliconflow.cn/v1/",    # 19
    "https://openrouter.ai/api/v1/",     # 20
    "https://api.groq.com/openai/v1/",   # 21
    "https://suflow.cloud/v1",            # 22  SuFlowAPI (Clove) partner gateway
]


def generate_ss_config(cpp_dir: Path) -> None:
    """Write g_ss_config.h with per-build random SS_KEY.
    Each APK build gets a unique XOR key for the secure string table,
    making static string extraction impossible across builds."""
    ss_key = random.randint(1, 255)  # non-zero, non-trivial
    n = len(SS_STRINGS)

    # Generate XOR-encrypted C arrays
    arrays = []
    for i, plain in enumerate(SS_STRINGS):
        enc = [b ^ ss_key for b in plain.encode()]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in enc)
        arrays.append(f"// ID {i}: \"{plain}\"\n"
                      f"static const uint8_t g_ss_{i}[] = {{{hex_bytes}}};\n"
                      f"#define SS_LEN_{i} {len(plain)}")

    # Build table arrays
    names = ", ".join(f"g_ss_{i}" for i in range(n))
    lens = ", ".join(f"SS_LEN_{i}" for i in range(n))

    # Build the array block (avoid backslash in f-string expression)
    array_block = "\n\n".join(arrays)

    content = f'''// Auto-generated per-build secure string table — DO NOT COMMIT
// Each APK build gets a randomized SS_KEY (XOR obfuscation).
// Generated by gen_payload_cpp.py at build time.

#ifndef YUNIAN_SS_CONFIG_H
#define YUNIAN_SS_CONFIG_H

#include <stdint.h>
#include <stddef.h>

#define SS_KEY 0x{ss_key:02X}u
#define SS_TABLE_SIZE {n}

{array_block}

static const uint8_t* g_ss_table[{n}] = {{ {names} }};
static const size_t g_ss_len_table[{n}] = {{ {lens} }};

#endif // YUNIAN_SS_CONFIG_H
'''
    config_path = cpp_dir / "g_ss_config.h"
    with open(config_path, 'w') as f:
        f.write(content)
    print(f"   SS config: {config_path} ({len(content)} bytes, key=0x{ss_key:02X})",
          file=sys.stderr)


def main():
    if len(sys.argv) < 6:
        print(f"Usage: {sys.argv[0]} <encrypted_dex> <output_cpp> <crc32_hex> <sm4_key_hex> <seed_hex>")
        sys.exit(1)

    enc_path = sys.argv[1]
    out_path = sys.argv[2]
    crc_hex = sys.argv[3] if sys.argv[3].startswith('0x') else f'0x{sys.argv[3]}'
    sm4_key_hex = sys.argv[4]
    xor_key_seed = int(sys.argv[5], 0)

    # ── Generate randomized algorithm constants ──
    lcg_mul = random_odd_u32()
    lcg_add = random.randint(1, 0xFFFFFFFF)
    xor_mult = random.randint(7, 253)       # non-zero, non-trivial
    xor_stride = random.choice([1, 2, 3, 4, 5, 7])  # coprime-ish to 4
    integrity_mul = random_odd_u32()         # random odd multiplier for integrity seed
    shell_names = generate_shell_names()     # random shell method/field names

    # Write config header
    cpp_dir = Path(out_path).parent
    generate_config(cpp_dir, lcg_mul, lcg_add, xor_mult, xor_stride,
                    integrity_mul, xor_key_seed, shell_names)

    # Write secure string table with per-build random XOR key
    generate_ss_config(cpp_dir)

    # Compute obfuscated key using randomized constants
    obf_key = compute_obfuscated_key(sm4_key_hex, xor_key_seed, xor_mult, xor_stride)

    # Scatter positions using randomized LCG
    positions = scatter_key_positions(xor_key_seed, lcg_mul, lcg_add)

    # Read encrypted payload
    with open(enc_path, 'rb') as f:
        enc_data = f.read()

    size = len(enc_data)
    print(f"Encrypted payload: {size:,} bytes, CRC32={crc_hex}, SM4 key={sm4_key_hex}",
          file=sys.stderr)

    # ── Split-key storage ──
    header_size = 256
    header = bytearray(header_size)
    for i in range(header_size):
        header[i] = random.randint(0, 255)
    for ki, pos in enumerate(positions):
        header[pos] = obf_key[ki]

    combined = bytes(header) + enc_data
    total_size = len(combined)

    # Generate C array
    lines = []
    for i in range(0, total_size, 40):
        chunk = combined[i:i + 40]
        line = "    " + ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 40 < total_size:
            line += ","
        lines.append(line)

    payload_str = "\n".join(lines)

    content = f'''// Auto-generated VMP payload — shell DEX packer
// Per-build random config: see g_vmp_config.h
// Payload size: {size:,} bytes (padded to 16-byte boundary)
// Expected CRC32: {crc_hex}
// Header: {header_size} bytes (key scattered at config-derived positions)
// Actual encrypted DEX starts at offset {header_size}

#include <stdint.h>
#include <stddef.h>

#define VMP_HEADER_SIZE {header_size}

extern const uint32_t g_vmp_payload_size __attribute__((used, visibility("default"))) = {total_size};
extern const uint32_t g_vmp_payload_crc32 __attribute__((used, visibility("default"))) = {crc_hex};

extern const uint8_t g_vmp_payload[] __attribute__((used, visibility("default"))) = {{
{payload_str}
}};
'''

    with open(out_path, 'w') as f:
        f.write(content)

    print(f"Written {len(content):,} chars → {out_path}", file=sys.stderr)
    print(f"Config → {cpp_dir / 'g_vmp_config.h'}", file=sys.stderr)


if __name__ == '__main__':
    main()
