#!/usr/bin/env python3
"""
pack_dex_fast.py — Fast DEX packer using sm4_tool (C++ SM4, matches dex-packer.cpp)

Replaces the old inline-C-compile approach with a pre-built sm4_tool binary.
SM4 encryption and CRC32 are computed by sm4_tool, guaranteeing byte-identical
results with the runtime decryption in liblianyu_security.so.

Usage:
  python3 tools/pack_dex_fast.py --apk <apk> --out <cpp_output>
"""

import os
import sys
import struct
import zipfile
import argparse
import subprocess
import tempfile

SM4_TOOL = '/tmp/sm4_tool'


def main():
    parser = argparse.ArgumentParser(description='VMP DEX Packer (fast)')
    parser.add_argument('--apk', required=True)
    parser.add_argument('--out', required=True)
    parser.add_argument('--key', help='SM4 key hex (32 chars)')
    args = parser.parse_args()

    # 1. Extract DEX from APK
    with zipfile.ZipFile(args.apk, 'r') as zf:
        try:
            dex_data = zf.read('classes.dex')
        except KeyError:
            for name in sorted(zf.namelist()):
                if '.dex' in name:
                    dex_data = zf.read(name)
                    break
            else:
                print("❌ No DEX in APK", file=sys.stderr)
                sys.exit(1)

    original_len = len(dex_data)
    print(f"📦 DEX: {original_len:,} bytes")

    # 2. Pad to 16-byte boundary
    pad = (16 - (original_len % 16)) % 16
    if pad:
        dex_data += b'\x00' * pad
    padded_len = len(dex_data)
    print(f"   Padded: {padded_len:,} bytes (+{pad})")

    # 3. Generate or parse key
    if args.key:
        key = bytes.fromhex(args.key)
    else:
        key = os.urandom(16)
    print(f"🔑 SM4 key: {key.hex()}")

    # 4. Encrypt using sm4_tool (matches dex-packer.cpp exactly)
    with tempfile.NamedTemporaryFile(suffix='.bin', delete=False) as f:
        f.write(dex_data)
        plain_path = f.name

    enc_path = plain_path + '.enc'

    result = subprocess.run(
        [SM4_TOOL, 'enc', plain_path, enc_path, key.hex()],
        capture_output=True, text=True, check=True
    )
    # sm4_tool prints CRC32 to stdout, info to stderr
    crc_line = result.stdout.strip()
    stderr_info = result.stderr.strip()
    if stderr_info:
        print(f"   {stderr_info}")

    # Parse CRC32 from stdout
    crc32_val = int(crc_line, 16)
    print(f"   CRC32: 0x{crc32_val:08X}")

    # 5. Read encrypted data
    with open(enc_path, 'rb') as f:
        encrypted = f.read()
    print(f"   Encrypted: {len(encrypted):,} bytes")

    # 6. XOR obfuscate key (must match deobfuscate_key in dex-packer.cpp)
    XOR_KEY_SEED = 0x9E3A7C51
    seed_bytes = struct.pack('<I', XOR_KEY_SEED)
    obfuscated = bytes(
        [(key[i] ^ seed_bytes[i % 4] ^ (i * 0x5D)) & 0xFF for i in range(16)]
    )

    # 7. Format C source with inline array
    payload_hex = ',\n    '.join(
        ', '.join(f'0x{b:02X}' for b in encrypted[i:i+16])
        for i in range(0, len(encrypted), 16)
    )

    c_source = f'''/*
 * AUTO-GENERATED by tools/pack_dex_fast.py — DO NOT EDIT
 * Encrypted DEX payload (SM4-ECB) + obfuscated key + CRC32
 *
 * Plaintext: {original_len:,} bytes (+{pad} pad) | Encrypted: {len(encrypted):,} bytes
 * CRC32:     0x{crc32_val:08X}
 * SM4 tool:  {SM4_TOOL}
 */

#include "dex-packer.h"

const uint8_t g_vmp_sm4_key[16] = {{
    {', '.join(f'0x{b:02X}' for b in obfuscated)}
}};

const uint32_t g_vmp_payload_crc32 = 0x{crc32_val:08X}U;

const uint8_t g_vmp_payload[] = {{
    {payload_hex}
}};

const uint32_t g_vmp_payload_size = {len(encrypted)}U;
'''

    with open(args.out, 'w') as f:
        f.write(c_source)

    # Cleanup
    os.unlink(plain_path)
    os.unlink(enc_path)

    print(f"✅ {args.out} ({len(encrypted):,} bytes, CRC32=0x{crc32_val:08X})")


if __name__ == '__main__':
    main()
